[build]
  command = "npm install"
#   publish = "./dist/"

[functions]
  external_node_modules = [
    "ejs",
    "express"
  ]
  included_files = [
    "./views/**/*",
    "./routes/**/*.js",
    "./public/**/*",
    "./data/**/*"
  ]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"
